export enum UserRole {
  ADMIN = "ADMIN",
  USER = "USER",
  TECHNICIAN = "TECHNICIAN",
  MANAGER = "MANAGER",
  FLEET_MANAGER = "FLEET_MANAGER",
  ANALYST = "ANALYST",
  SUPPORT_AGENT = "SUPPORT_AGENT"
}

export enum ConnectionStatus {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED"
}

export enum DeviceStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  DISCONNECTED = "DISCONNECTED",
  MAINTENANCE = "MAINTENANCE"
}

export enum VehicleStatus {
  NORMAL_EMISSION = "NORMAL_EMISSION",
  TOP_POLLUTING = "TOP_POLLUTING",
  INACTIVE_DISCONNECTED = "INACTIVE_DISCONNECTED",
  UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
}

export enum EmissionStatus {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH"
}

export enum FuelType {
  PETROL = "PETROL",
  DIESEL = "DIESEL",
  ELECTRIC = "ELECTRIC",
  HYBRID = "HYBRID"
}

export enum DeviceCategory {
  MOTORCYCLE = "MOTORCYCLE",
  CAR = "CAR",
  TRUCK = "TRUCK",
  TRICYCLE = "TRICYCLE",
  OTHER = "OTHER"
}

export enum CommunicationProtocol {
  MQTT = "MQTT",
  HTTP = "HTTP",
  SMS = "SMS"
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  SUSPENDED = "SUSPENDED",
  DEACTIVATED = "DEACTIVATED"
}

export enum NotificationType {
  HIGH_EMISSION_ALERT = "HIGH_EMISSION_ALERT",
  DIAGNOSTIC_FAULT_NOTIFICATION = "DIAGNOSTIC_FAULT_NOTIFICATION",
  FUEL_ANOMALY_ALERT = "FUEL_ANOMALY_ALERT",
  DEVICE_OFFLINE_WARNING = "DEVICE_OFFLINE_WARNING",
  SPEED_VIOLATION_ALERT = "SPEED_VIOLATION_ALERT"
}
